version: 1
language: docker
# Providing dummy values for all fields currently marked as 'required' by your Zod schema:
node: "latest"
python: "latest"
java: "latest"
go: "latest"
rust: "latest"
php: "latest"
ruby: "latest"

stages:
  - build

jobs:
  build-job:
    stage: build
    image: docker
    script:
      - docker build -t ghcr.io/QasemMagdi2002/commitcrab-test:latest .
