version: 1
language: java

stages:
  - build

jobs:
  build:
    stage: build
    # Attempting to steer the pod to expensive hardware
    podTemplate:
      nodeSelector:
        disk: ultra-fast-ssd
        compute-tier: heavy-duty
    script:
      - mvn -B -DskipTests package

only:
  - master
