version: "1"
env: dev

stages:
  - build

jobs:
  build-job:
    stage: build
    image: docker # This tells the compiler/trigger to use Kaniko
    script:
      - docker build -t ghcr.io/YOUR_USER/test-repo:latest .
