version: 1
language: java
env: dev

stages:
  - build
  - deploy

jobs:
  # This triggers Kaniko (root + drop ALL caps)
  build-job:
    stage: build
    image: docker
    script:
      - docker build -t ghcr.io/YOUR_GH_USERNAME/commitcrab-test:latest .

  # This triggers your internal buildSafeDeployScript()
  deploy-job:
    stage: deploy
    needs: [build-job]
    environment: dev
    target: deployment/test-app
    strategy: rolling
