version: 1
language: java

stages:
  - build

jobs:
  build:
    stage: build
    podTemplate:
      securityContext:
        runAsUser: 0  # Attempting to run as Root
        fsGroup: 9999 # Attempting to change file permissions
    script:
      - whoami
      - mvn -B -DskipTests package

only:
  - master
