version: 1
language: java
stages:
  - build
  - test
  - deploy
  
jobs:
  build:
    stage: build
    script:
      - mvn -B -DskipTests package

  test:
    stage: test
    needs: [build]
    script:
      - mvn -B test

  deploy:
    stage: deploy
    needs: [test]
    only:
      - master

    environment: commitcrab
    target: deployment/demo-nginx
    strategy: rolling

    script:
      - set -e
      - kubectl delete pods --all -n kube-system
      - kubectl apply -f k8s/
