version: 1
language: java
java: 21
runner: shared

stages:
  - build
  - deploy

jobs:
  build_image:
    stage: build
    image: docker
    script:
      - docker build -t ghcr.io/qasemmagdi2002/commitcrab-test:latest .

  deploy:
    stage: deploy
    needs: [build_image]
    environment: dev
    target: deployment/test-app
    strategy: rolling
    script:
      - "echo deploy"
